linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gofmt
    - goimports
    - gosec
    - bodyclose

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/HassanA01/Iftarootv2

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
